Develop
TheXtremeLabs/TheLab pull request #76
Opened 2023-03-23 21:45 UTC by MichaelStH

- create our own koltin bus (removed event bus library)
- refactor login classes optimize code + delete xml files
- schedule job activity to compose

2023-04-06 17:09 UTC, LVMVRQUXL requested changes
Bravo pour tout ce code ! Je t'ai proposé quelques modifications et évoqué quelques points.

2023-04-06 17:09 UTC, LVMVRQUXL commented on app/src/main/java/com/riders/thelab/ui/schedule/PreviewScheduleActivity.kt
> +                            viewModel.countDownQuery.isNotBlank().let {
Utilises plutôt la fonction `takeIf` comme suit :
`````kotlin
viewModel.countDownQuery.takeIf { it.isNotBlank() } // peut être convertit en référence
        ?.let { viewModel.startAlert(activity, it) }
        ?: UIManager.showCustomToast(
                activity,
                ToastTypeEnum.WARNING,
                "Field can't be empty. Please enter a valid number"
        )
```

2023-04-06 17:09 UTC, LVMVRQUXL commented on app/src/main/java/com/riders/thelab/ui/weather/PreviewWeather.kt
> +                viewModel.suggestions.take(10).forEachIndexed { index, label ->
Je ne connaissais pas la fonction `take` ; très intéressant !

2023-04-08 18:19 UTC, MichaelStH commented on app/src/main/java/com/riders/thelab/ui/login/PreviewLogin.kt
> +    val activity = context.findActivity() as LoginActivity
Avec Compose LocalContext.current renvoie le context dans lequel le composable est affiché.

Dans ce cas là le context sera une instance de Login Activity.

En revanche dans le cas où ce serait un Button, par exemple, que l'on utiliserait dans plusieurs activités dans ce cas si l'on appelle cette méthode le context ne sera pas forcément une instance de LoginActivity

2023-04-08 18:19 UTC, MichaelStH commented on app/src/main/java/com/riders/thelab/ui/mainactivity/fragment/weather/WeatherViewModel.kt
> +                    val weatherIconURL: String = it.currentWeather.weather?.get(0)?.icon!!
C'est pas encore fini

2023-04-10 12:29 UTC, LVMVRQUXL commented on app/src/main/java/com/riders/thelab/ui/login/PreviewLogin.kt
> +    val activity = context.findActivity() as LoginActivity
Je comprends mieux. Le risque serait d'appeler cette fonction dans une activité différente de `LoginActivity` : l'application planterait avec une exception.
Pour sécuriser le type de la variable `activity`, serait-il possible de fournir l'instance de l'activité en paramètre de la fonction `PreviewLoginContent` au lieu de forcer la conversion de cette manière ?

2023-05-19 17:46 UTC, merged